[supervisord]
nodaemon=true

[program:json-server]
command=npx json-server --host 0.0.0.0 --port 3000 --watch /app/db.json
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr

[program:nginx]
command=nginx -g "daemon off;"
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
